var ButtonCount=1,timeout=null;
function tm_slack_add_support_button(c,a,d,b){b="undefined"!==typeof b?b:null;c=tm_slack_add_button(c,a,null,"Support Request ("+tm_slack.user+")",d);$(c).attr({"tms-default":b}).unbind("click touchstart").bind("click touchstart",function(){tm_slack_support_popup($(this).attr("tms-channel"),$(this).attr("tms-user"),$(this).attr("tms-note"),$(this).attr("tms-default"));$("#slackFade, #slackPop").fadeIn(1E3);$(this).effect("transfer",{to:$("#slackPop")},800)});$(".slackLaunchWrapper").attr({title:"Make Support Request"});return c}
function tm_slack_add_button(c,a,d,b,f){d="undefined"!==typeof d?d:null;b="undefined"!==typeof b?b:null;var e="slackButton"+ButtonCount;$(c).append($("<div id='"+e+"Wrapper"+ButtonCount+"'>").addClass("slackLaunchWrapper").attr({title:"Post to Slack"}).append($("<input type='submit' id='"+e+"'>").addClass("slackLaunch").attr("value",a)));$("#"+e).attr({"tms-channel":d,"tms-user":b,"tms-note":f}).bind("click touchstart",function(){tm_slack_popup($(this).attr("tms-channel"),$(this).attr("tms-user"),
$(this).attr("tms-note"));$("#slackFade, #slackPop").fadeIn(1E3);$(this).effect("transfer",{to:$("#slackPop")},800)});ButtonCount++;return"#"+e}
function tm_slack_add_support_anchor(c,a,d,b){b="undefined"!==typeof b?b:null;c=tm_slack_add_anchor(c,a,null,"Support Request ("+tm_slack.user+")",d);$(c).attr({"tms-default":b}).unbind("click touchstart").bind("click touchstart",function(){tm_slack_support_popup($(this).attr("tms-channel"),$(this).attr("tms-user"),$(this).attr("tms-note"),$(this).attr("tms-default"));$("#slackFade, #slackPop").fadeIn(1E3);$(this).effect("transfer",{to:$("#slackPop")},800)});$(".slackLaunchWrapper").attr({title:"Make Support Request"});
return c}
function tm_slack_add_anchor(c,a,d,b,f){d="undefined"!==typeof d?d:null;b="undefined"!==typeof b?b:null;var e="slackButton"+ButtonCount;$(c).append($("<div id='"+e+"Wrapper"+ButtonCount+"'>").addClass("slackLaunchWrapper").attr({title:"Post to Slack"}).append($("<a id='"+e+"'>").addClass("slackLaunch").html("<i class='fa fa-support'>&nbsp;</i>"+a)));$("#"+e).attr({"tms-channel":d,"tms-user":b,"tms-note":f}).bind("click touchstart",function(){tm_slack_popup($(this).attr("tms-channel"),$(this).attr("tms-user"),$(this).attr("tms-note"));
$("#slackFade, #slackPop").fadeIn(1E3);$(this).effect("transfer",{to:$("#slackPop")},800)});ButtonCount++;return"#"+e}
function tm_slack_support_popup(c,a,d,b){tm_slack_popup(c,a,d);if(null==b||void 0===typeof b)b=0;$("#narrative").append($("<div id='suppText'>").html("Support provided between<br>7am and 6pm local time<br>UK business working days."));$("#commentWrapper").before($("<div id='productWrapper'>").addClass("slack-form-wrapper").append($("<label>").html("Product:")).append($("<select id='product'>").addClass("slack-form-item")));$.each({"--Select Product--":0,InterpreTA:"InterpreTA","Market Monitor":"Market Monitor",
Maverick:"Maverick",Research:"TradermadeWeb Research",TraderMade404:"TraderMade404","Other/General":"Other"},function(a,b){$("#product").append($("<option/>",{value:b,text:a}))});$("#product").val(b);$("#commentWrapper").before($("<div id='subjectWrapper'>").addClass("slack-form-wrapper").append($("<label>").html("Subject:")).append($("<textarea id='subject'>").addClass("slack-form-item")));$("#commentWrapper label").html("Issue:");$("#slack_submit").attr("value","Submit");tms_popup_locate("#slackPop");
$("#slack_submit").unbind("click touchstart").bind("click touchstart",function(){if(validate("support")){var a="User: "+tm_slack.user+"\nUser Email: "+tm_slack.email+"\nProduct: "+$("#slackPop #product").val()+"\n---\nSubject: "+$("#slackPop #subject").val()+"\nDescription: "+$("#slackPop #comment").val()+"\n---\nLocation: "+document.title+" \n<"+document.location.toString()+">";tm_slack_post(a,tm_slack.support,$("#slackPop #user").val());tm_slack.sf&&(a={},a.subject=$("#slackPop #subject").val(),
a.description=$("#slackPop #comment").val()+" \n<page:"+document.location.toString()+">\n"+document.title,a.product=$("#slackPop #product").val(),a.email=tm_slack.email,a.name=tm_slack.user,sf_post(a))}});$("#product").focus()}
function tm_slack_popup(c,a,d){$("body").append($("<div id=slackFade>"));$("body").append($("<div id=slackPop>").append($("<div id='narrative'>").html(d)));""!=c&&null!=c?$("#slackPop").append($("<input type='hidden' id='channel'>").val(c)):""==c&&$("#slackPop").append($("<div id='channelWrapper'>").addClass("slack-form-wrapper").append($("<label>").html("Channel:")).append($("<input type='text' id='channel'>").addClass("slack-form-item")));""!=a&&null!=a?$("#slackPop").append($("<input type='hidden' id='user'>").val(a)):
""==a&&$("#slackPop").append($("<div id='userWrapper'>").addClass("slack-form-wrapper").append($("<label>").html("Post Author:")).append($("<input type='text' id='user'>").addClass("slack-form-item")));$("#slackPop").append($("<div id='commentWrapper'>").addClass("slack-form-wrapper").append($("<label>").html("Posting:")).append($("<textarea id='comment'>").addClass("slack-form-item"))).append($("<input type='button' id='slack_submit' value='Post'>").addClass("slack-form-button")).append($("<input type='button' id='slack_cancel' value='Cancel'>").addClass("slack-form-button")).append($("<div id='slack_message'>"));
$("#slackFade").css("height",$(document).height()+"px");tms_popup_locate("#slackPop");$("#slack_submit").bind("click touchstart",function(){if(validate()){$("#slack_submit, #slack_cancel").prop("disabled",!0);$("#slack_message").html("<i class='fa fa-spinner fa-pulse'></i> Posting...").show();var a="User: "+tm_slack.user+"\nUser Email: "+tm_slack.email+"\nComment: "+$("#slackPop #comment").val()+"\n---\nLocation: "+document.title+" \n<"+document.location.toString()+">";tm_slack_post(a,$("#slackPop #channel").val(),
$("#slackPop #user").val())}});$("#slack_cancel").bind("click touchstart",function(){$("#slackFade").fadeOut(250);$("#slackPop").effect("transfer",{to:$("#slackButton1")},1E3,function(){$("#slackFade, #slackPop").remove()}).dequeue().fadeOut(800)});$("#comment").focus()}
function validate(c){$(".tms-failed").removeClass("tms-failed");$(".err").removeClass("err");$("#slack-message").html("").hide();var a=!0;5>$("#slackPop #comment").val().length&&($("#slackPop #comment").addClass("tms-failed"),a=!1);"support"==c&&(5>$("#slackPop #subject").val().length&&($("#slackPop #subject").addClass("tms-failed"),a=!1),0==$("#slackPop #product").val()&&($("#slackPop #product").addClass("tms-failed"),a=!1));a||$("#slack_message").html("Require highlighted information.").addClass("err").show();
return a}function tms_popup_locate(c){var a=($(window).height()-$(c).height())/4,d=($(window).width()-$(c).width())/2;$(c).css({top:a,left:d})}
function tm_slack_post(c,a,d){var b={};b.text=c;b.icon_url=tm_slack.url+"/images/mavround.gif";b.username="undefined"!==typeof d?d:"Website User";a&&(b.channel=a);$.ajax({data:"payload="+encodeURIComponent(JSON.stringify(b)),type:"POST",url:"/sites/all/modules/tm_slack/tm_slack.proxy.php",success:function(a){"ok"==a.toLowerCase()?($("#slack_message").fadeOut(function(){$(this).html("<i class='fa fa-check'></i>&nbsp;Posting Success").addClass("ok").show()}),timeout&&clearTimeout(timeout),timeout=setTimeout(function(){$("#slackFade").fadeOut(250);
$("#slackPop").effect("transfer",{to:$("#slackButton1")},1E3,function(){$("#slackFade, #slackPop").remove()}).dequeue().fadeOut(800)},5E3)):(console.log("Slack Error: Unexpected response - "+a),timeout&&clearTimeout(timeout),$("#slack_message").fadeOut(function(){$(this).html("<i class='fa fa-times'></i>&nbsp;Posting Error. "+a).addClass("err").show()}));$("#slack_submit,#slack_cancel").prop("disabled",!1)},error:function(a){console.log("Slack Error: Ajax fail - "+a);$("#slack_submit,#slack_cancel").prop("disabled",
!1);timeout&&clearTimeout(timeout);$("#slack_message").html("<i class='fa fa-times'></i>&nbsp;Posting Error. "+a.responseText).addClass("err")}})}
function sf_post(c){if(!tm_slack.sf)return!0;c.sf_destination="case";$.ajax({data:"payload="+encodeURIComponent(JSON.stringify(c)),type:"POST",url:"/sites/all/modules/tm_utilities/includes/salesforce_poster/sf-form-submitter.php",success:function(a){isset(a)&&""!=a&&(a=JSON.parse(a));"ok"==a.result.toLowerCase()?($("#slack_message").html("<i class='fa fa-check'></i>&nbsp;Posting Success").addClass("ok"),timeout&&clearTimeout(timeout),timeout=setTimeout(function(){$("#slackFade, #slackPop").fadeOut(function(){$("#slackFade, #slackPop").remove()})},
1500)):(console.log("Salesforce Error: Unexpected response - "+a),timeout&&clearTimeout(timeout),$("#slack_message").html("<i class='fa fa-times'></i>&nbsp;Posting Error. "+a.result).addClass("err"))},error:function(a){console.log("Salesforce Error: Ajax fail - "+a);timeout&&clearTimeout(timeout);$("#slack_message").html("<i class='fa fa-times'></i>&nbsp;Posting Error. "+a.responseText).addClass("err")}})};
